#!/bin/bash

function get_all_secrets() {
  oc get secrets --all-namespaces -o json | jq -r '.items[] | . as $item | .data? | select(.) | to_entries[] | [$item.metadata.namespace, $item.metadata.name, .key, .value] | join(" ")'
}

function check_certificates() {
    local ret=0
	while read -s myinp 
	do
		if [ "${myinp//END CERTIFICATE}" != "${myinp}" ]; then
			crt="${crt}${myinp}\n"
			if ! printf "%b\n" "${crt}" | openssl x509 -checkend 604800 &> /dev/null; then
              echo ""
              ret=1
            fi
			printf "%b\n" "${crt}" | openssl x509 -subject -issuer -noout -startdate -enddate
			crt=""
		else
			crt="${crt}${myinp}\n"
		fi
	done <<< "$1"

    return $ret
}

function validate_secret() {
    local ret=0
    local ns="$1"
    local name="$2"
    local key="$3"
    local value_b64="$4"
    local value="$(echo "$value_b64" | base64 -d)"

    echo -n "$ns $name $key "
    if check_certificates "$value" ; then
        echo "OK"
    else
        echo "FAILED"
        ret=1
    fi

    return $ret
}

errors=0

while IFS= read -r line
do
    if ! validate_secret $line; then
        ((errors++))
    fi
done <<< "$(get_all_secrets)"

echo "Found $errors errors!"
[ $errors == 0 ]

